name: "Hertta"
version: "0.10.0"
slug: "hertta_addon"
description: "Home energy optimization with Hertta and Predicer"
url: "https://github.com/jeenou/hertta-hass-addon"
image: "ghcr.io/jeenou/{arch}-hertta-addon"

arch:
  - amd64

startup: services
boot: auto
init: false

ingress: true
ingress_port: 4001
panel_icon: "mdi:chart-line"
panel_title: "Hertta"
watchdog: "http://[HOST]:4001/hertta-health"

homeassistant_api: true

options:
  log_level: info

schema:
  log_level: list(off|fatal|error|warning|info|debug|trace)
